// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHTJqqPJ-bQxagrgX_5i1Hu0G33gp5T0E',
    appId: '1:64372665663:web:eb98f8cdd17139c11c778a',
    messagingSenderId: '64372665663',
    projectId: 'reactnativedemo-28bd1',
    authDomain: 'reactnativedemo-28bd1.firebaseapp.com',
    databaseURL: 'https://reactnativedemo-28bd1-default-rtdb.firebaseio.com',
    storageBucket: 'reactnativedemo-28bd1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB51DGG8WXjHghcNj4Ly9Y0TvEV_mj29zQ',
    appId: '1:64372665663:android:6dc7d21be9c59ed61c778a',
    messagingSenderId: '64372665663',
    projectId: 'reactnativedemo-28bd1',
    databaseURL: 'https://reactnativedemo-28bd1-default-rtdb.firebaseio.com',
    storageBucket: 'reactnativedemo-28bd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHTFNrsEMKvYbG0qfcePxSlhXd-lbAlPk',
    appId: '1:64372665663:ios:4ef9d00a7804242c1c778a',
    messagingSenderId: '64372665663',
    projectId: 'reactnativedemo-28bd1',
    databaseURL: 'https://reactnativedemo-28bd1-default-rtdb.firebaseio.com',
    storageBucket: 'reactnativedemo-28bd1.appspot.com',
    iosClientId:
        '64372665663-t01aolahckuc5535dfts4l7ce1ci28vc.apps.googleusercontent.com',
    iosBundleId: 'com.example.carogame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHTFNrsEMKvYbG0qfcePxSlhXd-lbAlPk',
    appId: '1:64372665663:ios:4ef9d00a7804242c1c778a',
    messagingSenderId: '64372665663',
    projectId: 'reactnativedemo-28bd1',
    databaseURL: 'https://reactnativedemo-28bd1-default-rtdb.firebaseio.com',
    storageBucket: 'reactnativedemo-28bd1.appspot.com',
    iosClientId:
        '64372665663-t01aolahckuc5535dfts4l7ce1ci28vc.apps.googleusercontent.com',
    iosBundleId: 'com.example.carogame',
  );
}
